# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_name', models.CharField(max_length=128, verbose_name='\u6848\u4f8b\u540d\u79f0')),
                ('testcase_content', models.CharField(max_length=128, verbose_name='\u6848\u4f8b\u63cf\u8ff0')),
                ('status', models.CharField(blank=True, choices=[(b'0', '\u65b0\u5efa'), (b'1', '\u6267\u884c\u4e2d'), (b'2', '\u6d4b\u8bd5\u6210\u529f'), (b'3', '\u6d4b\u8bd5\u5931\u8d25')], max_length=30, null=True, verbose_name='\u6d4b\u8bd5\u4efb\u52a1\u72b6\u6001')),
                ('charge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d1f\u8d23\u4eba')),
            ],
        ),
    ]
