# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='charge_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='anli\u8d1f\u8d23\u4eba'),
        ),
    ]
