# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20181226_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='caseOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u8d1f\u8d23\u4eba\u59d3\u540d')),
                ('phone', models.CharField(max_length=50, verbose_name='\u8d1f\u8d23\u4eba\u624b\u673a')),
                ('qq', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d1f\u8d23\u4ebaQQ')),
                ('weChat', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d1f\u8d23\u4eba\u5fae\u4fe1')),
            ],
        ),
        migrations.AlterField(
            model_name='testcase',
            name='charge_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.caseOwner', verbose_name='anli\u8d1f\u8d23\u4eba'),
        ),
    ]
