# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20181226_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='caseOwner',
            new_name='productionUser',
        ),
    ]
