# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('case', '0004_auto_20181226_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='project_own',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='\u6d4b\u8bd5\u6848\u4f8b\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='charge_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='anli\u8d1f\u8d23\u4eba'),
        ),
    ]
