# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=40, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('p_desc', models.CharField(max_length=40, unique=True, verbose_name='\u9879\u76ee\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250, verbose_name='\u5b50\u4efb\u52a1\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(blank=True, null=True, verbose_name='t_id')),
                ('task_name', models.CharField(max_length=64, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('task_content', models.TextField(blank=True, max_length=255, verbose_name='\u4efb\u52a1\u5185\u5bb9')),
                ('expect_time', models.IntegerField(blank=True, null=True, verbose_name='\u9884\u8ba1\u9700\u8981\u65f6\u95f4')),
                ('status', models.CharField(blank=True, choices=[(b'0', '\u65b0\u5efa'), (b'1', '\u6267\u884c\u4e2d'), (b'2', '\u6267\u884c\u6210\u529f'), (b'3', '\u6267\u884c\u5931\u8d25')], max_length=30, null=True, verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='task_img/', verbose_name='\u6b65\u9aa4\u56fe')),
                ('start_time', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('charge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_user', to=settings.AUTH_USER_MODEL, verbose_name='\u8d23\u4efb\u4eba')),
                ('execute_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execute_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='project.Project', verbose_name='\u6240\u5c5e\u9879\u76ee')),
                ('sub_task', models.ManyToManyField(to='project.subtask', verbose_name='\u5b50\u4efb\u52a1')),
            ],
        ),
    ]
