# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-28 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(blank=True, choices=[(b'0', '\u65b0\u5efa'), (b'1', '\u6267\u884c\u4e2d'), (b'2', '\u6267\u884c\u6210\u529f'), (b'3', '\u6267\u884c\u5931\u8d25')], max_length=30, null=True, verbose_name='\u5b50\u4efb\u52a1\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='task',
            name='execute_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execute_user', to=settings.AUTH_USER_MODEL, verbose_name='\u6267\u884c\u4eba'),
        ),
    ]
