# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181228_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(blank=True, choices=[(b'0', '\u6210\u529f'), (b'1', '\u5931\u8d25'), (b'2', '\u672a\u5f00\u59cb')], max_length=30, null=True, verbose_name='\u5b50\u4efb\u52a1\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[(0, '\u672a\u5f00\u59cb'), (1, '\u6267\u884c\u4e2d'), (2, '\u6267\u884c\u6210\u529f'), (3, '\u6267\u884c\u5931\u8d25')], default=0, max_length=30, null=True, verbose_name='\u4efb\u52a1\u72b6\u6001'),
        ),
    ]
