# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190110_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_task',
        ),
        migrations.AddField(
            model_name='task',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_subtask', to='project.subtask', verbose_name='\u5b50\u4efb\u52a1'),
        ),
    ]
