# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190110_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_task',
        ),
        migrations.AddField(
            model_name='task',
            name='sub_task',
            field=models.ManyToManyField(to='project.subtask', verbose_name='\u5b50\u4efb\u52a1'),
        ),
    ]
