# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190110_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(blank=True, choices=[(b'0', '\u672a\u5f00\u59cb'), (b'1', '\u6210\u529f'), (b'2', '\u5931\u8d25')], max_length=30, null=True, verbose_name='\u5b50\u4efb\u52a1\u72b6\u6001'),
        ),
    ]
