# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-16 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190110_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_current',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f53\u524d\u9879\u76ee'),
        ),
    ]
