# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-20 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_project_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='charge_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_charge_user', to=settings.AUTH_USER_MODEL, verbose_name='\u8d23\u4efb\u4eba'),
        ),
    ]
